version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env.local
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

